FROM node:22-alpine AS build

WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY . .

ARG VITE_MODE=production

RUN npm run build -- --mode ${VITE_MODE}

FROM nginx:stable-alpine

COPY --from=build /app/dist /usr/share/nginx/html

# Nginx-Konfiguration für Vue-SPA-Routing
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]