export const countries = [
    { name: "Afghanistan", code: "AF", dialCode: "+93" },
    { name: "Albanien", code: "AL", dialCode: "+355" },
    { name: "Algerien", code: "DZ", dialCode: "+213" },
    { name: "Andorra", code: "AD", dialCode: "+376" },
    { name: "Angola", code: "AO", dialCode: "+244" },
    { name: "Antigua und Barbuda", code: "AG", dialCode: "+1-268" },
    { name: "Argentinien", code: "AR", dialCode: "+54" },
    { name: "Armenien", code: "AM", dialCode: "+374" },
    { name: "Australien", code: "AU", dialCode: "+61" },
    { name: "Österreich", code: "AT", dialCode: "+43" },
    { name: "Aserbaidschan", code: "AZ", dialCode: "+994" },
    { name: "Bahamas", code: "BS", dialCode: "+1-242" },
    { name: "Bahrain", code: "BH", dialCode: "+973" },
    { name: "Bangladesch", code: "BD", dialCode: "+880" },
    { name: "Barbados", code: "BB", dialCode: "+1-246" },
    { name: "Belarus", code: "BY", dialCode: "+375" },
    { name: "Belgien", code: "BE", dialCode: "+32" },
    { name: "Belize", code: "BZ", dialCode: "+501" },
    { name: "Benin", code: "BJ", dialCode: "+229" },
    { name: "Bhutan", code: "BT", dialCode: "+975" },
    { name: "Bolivien", code: "BO", dialCode: "+591" },
    { name: "Bosnien und Herzegowina", code: "BA", dialCode: "+387" },
    { name: "Botswana", code: "BW", dialCode: "+267" },
    { name: "Brasilien", code: "BR", dialCode: "+55" },
    { name: "Bulgarien", code: "BG", dialCode: "+359" },
    { name: "Kanada", code: "CA", dialCode: "+1" },
    { name: "Chile", code: "CL", dialCode: "+56" },
    { name: "China", code: "CN", dialCode: "+86" },
    { name: "Kolumbien", code: "CO", dialCode: "+57" },
    { name: "Kroatien", code: "HR", dialCode: "+385" },
    { name: "Kuba", code: "CU", dialCode: "+53" },
    { name: "Dänemark", code: "DK", dialCode: "+45" },
    { name: "Dominikanische Republik", code: "DO", dialCode: "+1-809" },
    { name: "Ecuador", code: "EC", dialCode: "+593" },
    { name: "Ägypten", code: "EG", dialCode: "+20" },
    { name: "Estland", code: "EE", dialCode: "+372" },
    { name: "Finnland", code: "FI", dialCode: "+358" },
    { name: "Frankreich", code: "FR", dialCode: "+33" },
    { name: "Deutschland", code: "DE", dialCode: "+49" },
    { name: "Griechenland", code: "GR", dialCode: "+30" },
    { name: "Hongkong", code: "HK", dialCode: "+852" },
    { name: "Ungarn", code: "HU", dialCode: "+36" },
    { name: "Indien", code: "IN", dialCode: "+91" },
    { name: "Indonesien", code: "ID", dialCode: "+62" },
    { name: "Irland", code: "IE", dialCode: "+353" },
    { name: "Israel", code: "IL", dialCode: "+972" },
    { name: "Italien", code: "IT", dialCode: "+39" },
    { name: "Japan", code: "JP", dialCode: "+81" },
    { name: "Kasachstan", code: "KZ", dialCode: "+7" },
    { name: "Kenia", code: "KE", dialCode: "+254" },
    { name: "Lettland", code: "LV", dialCode: "+371" },
    { name: "Litauen", code: "LT", dialCode: "+370" },
    { name: "Luxemburg", code: "LU", dialCode: "+352" },
    { name: "Malaysia", code: "MY", dialCode: "+60" },
    { name: "Malta", code: "MT", dialCode: "+356" },
    { name: "Mexiko", code: "MX", dialCode: "+52" },
    { name: "Niederlande", code: "NL", dialCode: "+31" },
    { name: "Neuseeland", code: "NZ", dialCode: "+64" },
    { name: "Nigeria", code: "NG", dialCode: "+234" },
    { name: "Norwegen", code: "NO", dialCode: "+47" },
    { name: "Pakistan", code: "PK", dialCode: "+92" },
    { name: "Panama", code: "PA", dialCode: "+507" },
    { name: "Paraguay", code: "PY", dialCode: "+595" },
    { name: "Peru", code: "PE", dialCode: "+51" },
    { name: "Philippinen", code: "PH", dialCode: "+63" },
    { name: "Polen", code: "PL", dialCode: "+48" },
    { name: "Portugal", code: "PT", dialCode: "+351" },
    { name: "Rumänien", code: "RO", dialCode: "+40" },
    { name: "Russland", code: "RU", dialCode: "+7" },
    { name: "Saudi-Arabien", code: "SA", dialCode: "+966" },
    { name: "Singapur", code: "SG", dialCode: "+65" },
    { name: "Slowakei", code: "SK", dialCode: "+421" },
    { name: "Slowenien", code: "SI", dialCode: "+386" },
    { name: "Südafrika", code: "ZA", dialCode: "+27" },
    { name: "Südkorea", code: "KR", dialCode: "+82" },
    { name: "Spanien", code: "ES", dialCode: "+34" },
    { name: "Schweden", code: "SE", dialCode: "+46" },
    { name: "Schweiz", code: "CH", dialCode: "+41" },
    { name: "Thailand", code: "TH", dialCode: "+66" },
    { name: "Tunesien", code: "TN", dialCode: "+216" },
    { name: "Türkei", code: "TR", dialCode: "+90" },
    { name: "Ukraine", code: "UA", dialCode: "+380" },
    { name: "Vereinigte Arabische Emirate", code: "AE", dialCode: "+971" },
    { name: "Vereinigtes Königreich", code: "GB", dialCode: "+44" },
    { name: "Vereinigte Staaten", code: "US", dialCode: "+1" },
    { name: "Vietnam", code: "VN", dialCode: "+84" }
  ];
  
  export default countries;
  